added_pagination
dima0208/test_ukad pull request #3
Opened 2023-02-23 09:28 UTC by dima0208

2023-02-23 09:46 UTC, ArturNagaycev approved these changes
Good job!
It'll be better to see your project not installing it locally. 
Maybe you will deploy it somewhere next time))

2023-02-24 10:39 UTC, IgorNovikov10 requested changes

2023-02-24 10:39 UTC, IgorNovikov10 commented on src/pages/Products/Products.js
> +        <Pagination onPageChange={onPageChange} />
you can simply pass referense to setCurrentPage function here instead of creating onPageChange handler that just passes pageNumber to setter function

2023-02-24 10:39 UTC, IgorNovikov10 commented on src/pages/Products/Products.js
> +    setCurrentPage(pageNumber);
add pageNumber to query string in order to fetch corresponding bunch of items on page reload

2023-02-24 10:39 UTC, IgorNovikov10 commented on src/pages/Products/Products.js
> +        <Pagination onPageChange={onPageChange} />
also, it would be nice to scroll the page to the top of the list when the cuurent page is changing

2023-02-24 19:57 UTC, merged